# Site settings
title: 余生时光
SEOTitle: 余生时光
header-img: https://blog-img.fanhai-cloud.com/home-bg.jpg
email: zjd0418@gmail.com
description: "聊聊java技术"
keyword: ""
url: "http://www.shadow123.net"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     huxpro
zhihu_username:     shadow-74-5
github_username:    zhangjiadong
twitter_username:  zjd0418
# facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: shadow
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings  暂时停掉了
# Baidu Analytics
ba_track_id: test
# Google Analytics
ga_track_id: test            # Format: UA-xxxxxx-xx
ga_domain: shadow123.net



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "编程、旅游、写作。"
sidebar-avatar: https://blog-img.fanhai-cloud.com/avatar-shadow.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Shadow Blog",
        href: "http://shadow123.net"
    },{
        title: "Nothing",
        href: "#"
    }
]
