# Site settings
title: 张家东
description: 'Life is short,I use Java!'
url: 'http://zhangjiadong.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
duoshuo_shortname: shadow0418

encoding: utf-8

author:
  name: '张家东'
  email: zjd0418@gmail.com
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  zhangjiadong
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

